# Generated by Django 4.0 on 2023-05-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
