# Generated by Django 3.2 on 2023-06-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0004_auto_20230519_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('img', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Изображение')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.category', verbose_name='Катеогрия')),
            ],
        ),
    ]
