# Generated by Django 3.2 on 2023-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=32)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_of_create',),
            },
        ),
    ]
