# Generated by Django 3.2 on 2023-05-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0002_category_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
        migrations.AddField(
            model_name='flat',
            name='object_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flats_sale.object', verbose_name='Объект'),
        ),
    ]
